// This file is generated by omniidl (C++ backend)- omniORB_4_2. Do not edit.

#include "add.hh"
#include <omniORB4/IOP_S.h>
#include <omniORB4/IOP_C.h>
#include <omniORB4/callDescriptor.h>
#include <omniORB4/callHandle.h>
#include <omniORB4/objTracker.h>


OMNI_USING_NAMESPACE(omni)

static const char* _0RL_library_version = omniORB_4_2;



int_Add_ptr int_Add_Helper::_nil() {
  return ::int_Add::_nil();
}

::CORBA::Boolean int_Add_Helper::is_nil(::int_Add_ptr p) {
  return ::CORBA::is_nil(p);

}

void int_Add_Helper::release(::int_Add_ptr p) {
  ::CORBA::release(p);
}

void int_Add_Helper::marshalObjRef(::int_Add_ptr obj, cdrStream& s) {
  ::int_Add::_marshalObjRef(obj, s);
}

int_Add_ptr int_Add_Helper::unmarshalObjRef(cdrStream& s) {
  return ::int_Add::_unmarshalObjRef(s);
}

void int_Add_Helper::duplicate(::int_Add_ptr obj) {
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
}

int_Add_ptr
int_Add::_duplicate(::int_Add_ptr obj)
{
  if (obj && !obj->_NP_is_nil())  omni::duplicateObjRef(obj);
  return obj;
}

int_Add_ptr
int_Add::_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_realNarrow(_PD_repoId);
  return e ? e : _nil();
}


int_Add_ptr
int_Add::_unchecked_narrow(::CORBA::Object_ptr obj)
{
  if (!obj || obj->_NP_is_nil() || obj->_NP_is_pseudo()) return _nil();
  _ptr_type e = (_ptr_type) obj->_PR_getobj()->_uncheckedNarrow(_PD_repoId);
  return e ? e : _nil();
}

int_Add_ptr
int_Add::_nil()
{
#ifdef OMNI_UNLOADABLE_STUBS
  static _objref_int_Add _the_nil_obj;
  return &_the_nil_obj;
#else
  static _objref_int_Add* _the_nil_ptr = 0;
  if (!_the_nil_ptr) {
    omni::nilRefLock().lock();
    if (!_the_nil_ptr) {
      _the_nil_ptr = new _objref_int_Add;
      registerNilCorbaObject(_the_nil_ptr);
    }
    omni::nilRefLock().unlock();
  }
  return _the_nil_ptr;
#endif
}

const char* int_Add::_PD_repoId = "IDL:int_Add:1.0";


_objref_int_Add::~_objref_int_Add() {
  
}


_objref_int_Add::_objref_int_Add(omniIOR* ior, omniIdentity* id) :
   omniObjRef(::int_Add::_PD_repoId, ior, id, 1)
   
   
{
  _PR_setobj(this);
}

void*
_objref_int_Add::_ptrToObjRef(const char* id)
{
  if (id == ::int_Add::_PD_repoId)
    return (::int_Add_ptr) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (::CORBA::Object_ptr) this;

  if (omni::strMatch(id, ::int_Add::_PD_repoId))
    return (::int_Add_ptr) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (::CORBA::Object_ptr) this;

  return 0;
}


//
// Code for int_Add::add

// Proxy call descriptor class. Mangled signature:
//  _clong_i_clong_i_clong
class _0RL_cd_523938fdb4fa52bf_00000000
  : public omniCallDescriptor
{
public:
  inline _0RL_cd_523938fdb4fa52bf_00000000(LocalCallFn lcfn, const char* op_, size_t oplen, _CORBA_Boolean upcall=0)
    : omniCallDescriptor(lcfn, op_, oplen, 0, _user_exns, 0, upcall)
  {
    
  }
  
  void marshalArguments(cdrStream&);
  void unmarshalArguments(cdrStream&);

  void unmarshalReturnedValues(cdrStream&);
  void marshalReturnedValues(cdrStream&);
  
  
  static const char* const _user_exns[];

  ::CORBA::Long arg_0;
  ::CORBA::Long arg_1;
  ::CORBA::Long result;
};

void _0RL_cd_523938fdb4fa52bf_00000000::marshalArguments(cdrStream& _n)
{
  arg_0 >>= _n;
  arg_1 >>= _n;

}

void _0RL_cd_523938fdb4fa52bf_00000000::unmarshalArguments(cdrStream& _n)
{
  (::CORBA::Long&)arg_0 <<= _n;
  (::CORBA::Long&)arg_1 <<= _n;

}

void _0RL_cd_523938fdb4fa52bf_00000000::marshalReturnedValues(cdrStream& _n)
{
  result >>= _n;

}

void _0RL_cd_523938fdb4fa52bf_00000000::unmarshalReturnedValues(cdrStream& _n)
{
  (::CORBA::Long&)result <<= _n;

}

const char* const _0RL_cd_523938fdb4fa52bf_00000000::_user_exns[] = {
  0
};

// Local call call-back function.
static void
_0RL_lcfn_523938fdb4fa52bf_10000000(omniCallDescriptor* cd, omniServant* svnt)
{
  _0RL_cd_523938fdb4fa52bf_00000000* tcd = (_0RL_cd_523938fdb4fa52bf_00000000*)cd;
  _impl_int_Add* impl = (_impl_int_Add*) svnt->_ptrToInterface(int_Add::_PD_repoId);
  tcd->result = impl->add(tcd->arg_0, tcd->arg_1);


}

::CORBA::Long _objref_int_Add::add(::CORBA::Long a1, ::CORBA::Long a2)
{
  _0RL_cd_523938fdb4fa52bf_00000000 _call_desc(_0RL_lcfn_523938fdb4fa52bf_10000000, "add", 4);
  _call_desc.arg_0 = a1;
  _call_desc.arg_1 = a2;

  _invoke(_call_desc);
  return _call_desc.result;


}

_pof_int_Add::~_pof_int_Add() {}


omniObjRef*
_pof_int_Add::newObjRef(omniIOR* ior, omniIdentity* id)
{
  return new ::_objref_int_Add(ior, id);
}


::CORBA::Boolean
_pof_int_Add::is_a(const char* id) const
{
  if (omni::ptrStrMatch(id, ::int_Add::_PD_repoId))
    return 1;
  
  return 0;
}

const _pof_int_Add _the_pof_int__Add;

_impl_int_Add::~_impl_int_Add() {}


::CORBA::Boolean
_impl_int_Add::_dispatch(omniCallHandle& _handle)
{
  const char* op = _handle.operation_name();

  if (omni::strMatch(op, "add")) {

    _0RL_cd_523938fdb4fa52bf_00000000 _call_desc(_0RL_lcfn_523938fdb4fa52bf_10000000, "add", 4, 1);
    
    _handle.upcall(this,_call_desc);
    return 1;
  }


  return 0;
}

void*
_impl_int_Add::_ptrToInterface(const char* id)
{
  if (id == ::int_Add::_PD_repoId)
    return (::_impl_int_Add*) this;
  
  if (id == ::CORBA::Object::_PD_repoId)
    return (void*) 1;

  if (omni::strMatch(id, ::int_Add::_PD_repoId))
    return (::_impl_int_Add*) this;
  
  if (omni::strMatch(id, ::CORBA::Object::_PD_repoId))
    return (void*) 1;
  return 0;
}

const char*
_impl_int_Add::_mostDerivedRepoId()
{
  return ::int_Add::_PD_repoId;
}

POA_int_Add::~POA_int_Add() {}

